insert into temporada (nom)
values
  ('2025/2026'),
  ('2026/2027')
on conflict (nom) do nothing;

with t as (
  select id from temporada where nom = '2025/2026'
)
insert into equip (temporada_id, nom, categoria, url_fcf)
select t.id, v.nom, v.categoria, v.url_fcf
from t
join (values
  ('Primer Equip', 'Senior', null),
  ('Filial', 'Senior', null),
  ('Minis', 'Minis', null),
  ('S7', 'Futbol Base Masculi', null),
  ('S8', 'Futbol Base Masculi', null),
  ('S9', 'Futbol Base Masculi', null),
  ('S10', 'Futbol Base Masculi', null),
  ('S11', 'Futbol Base Masculi', null),
  ('S12', 'Futbol Base Masculi', null),
  ('S13', 'Futbol Base Masculi', null),
  ('S14', 'Futbol Base Masculi', null),
  ('S16 (Cadet)', 'Futbol Base Masculi', null),
  ('Juvenil Masculi - A', 'Futbol Base Masculi', null),
  ('Alevi Femeni', 'Futbol Base Femeni', null),
  ('Infantil-Cadet Femeni', 'Futbol Base Femeni', null),
  ('Juvenil Femeni', 'Futbol Base Femeni', null),
  ('Juvenil Masculi - B', 'Futbol Base Masculi', null)
) v(nom, categoria, url_fcf)
  on true
on conflict (temporada_id, nom) do nothing;

with t as (
  select id from temporada where nom = '2025/2026'
),
 e as (
  select id, nom from equip where temporada_id = (select id from t)
),
 v as (
  select * from (values
    ('Primer Equip', 'LLUÍS MARTÍNEZ, LLUÍS'),
    ('Primer Equip', 'ROVIRA DE PAZ, JOAN'),
    ('Primer Equip', 'CASALS ASENSIO, ALBERT'),
    ('Primer Equip', 'GONZÁLEZ TRISTANY, VICENÇ'),
    ('Primer Equip', 'RATERA VILLEGAS, XAVIER'),
    ('Primer Equip', 'ROLDAN GIMENEZ, ANTONIO'),
    ('Primer Equip', 'LIRIA RUIZ, ANTONIO'),
    ('Primer Equip', 'MOLINA BEA, VICTOR'),
    ('Primer Equip', 'GALERA ARNAU, URIEL'),
    ('Primer Equip', 'LORCA PARRA, AITOR'),
    ('Primer Equip', 'SEGURA URRUTIA, AITOR'),
    ('Primer Equip', 'LORCA CORTADA, MARC'),
    ('Primer Equip', 'SERRA SEGUÉS, ANIOL'),
    ('Primer Equip', 'SANZ GARCIA, GUILLEM'),
    ('Primer Equip', 'BIGI PARROT SILVA, LORENÇO'),
    ('Primer Equip', 'GUIJARRO IGLESIAS, MARC'),
    ('Primer Equip', 'PALOMO RAYA, RUBEN'),
    ('Primer Equip', 'COTS OLIVÉ, BIEL'),
    ('Primer Equip', 'VILADOMAT SALLES, JOAN'),
    ('Primer Equip', 'PÉREZ FONTAN, RAFEL'),
    ('Primer Equip', 'NAVARRO PEREZ, IKER'),
    ('Primer Equip', 'TORRES GONZALEZ, ALEJANDRO'),

    ('Filial', 'DE LA PAZ BELMONTE, PEDRO CARLOS'),
    ('Filial', 'TOMAS FLORES, LLUÍS'),
    ('Filial', 'MALPICA HARO, CARLOS'),
    ('Filial', 'VILA RODRIGEZ, JOSEP'),
    ('Filial', 'ALARAN , QUADRI BOLAJI'),
    ('Filial', 'CUGUERÓ MUIXÍ, MARC'),
    ('Filial', 'GONZÁLEZ BERRUEZO, VÍCTOR'),
    ('Filial', 'CARREÑO DELGADO, ARAN'),
    ('Filial', 'JURADO RUIZ, ARTUR'),
    ('Filial', 'GRIFUL ARRIETA, GABRIEL'),
    ('Filial', 'VIDAL ROCA, ROGER'),
    ('Filial', 'VILÀ SALVADOR, FÈLIX'),
    ('Filial', 'HERNANDEZ PONS, IZAN'),
    ('Filial', 'PEREZ ARJONA, XAVIER'),
    ('Filial', 'FONTAN SANCHEZ, POL'),
    ('Filial', 'RIVERA TORRENTS, POL'),
    ('Filial', 'DEIG ESTRUCH, ROGER'),
    ('Filial', 'TOLEDO SANCHEZ, IVAN'),
    ('Filial', 'TREMP MORDIK, ADRIAN'),
    ('Filial', 'VILARMAU MURRAY, MARC'),
    ('Filial', 'SANCHEZ PEREIRA, MIQUEL'),
    ('Filial', 'MONTOYA XANDRI, NOEL'),
    ('Filial', 'COTS OLIVE, BIEL'),
    ('Filial', 'BENAIGES SOTO, RUBEN'),
    ('Filial', 'JANE VILA, LLUC'),

    ('Alevi Femeni', 'VILALTA MOLNER, MAR'),
    ('Alevi Femeni', 'PEREZ RODRIGUEZ, CLAUDIA'),
    ('Alevi Femeni', 'MARTINEZ RODRIGUEZ, CHARLOTTE'),
    ('Alevi Femeni', 'BERRUEZO FERNANDEZ, LAIA'),
    ('Alevi Femeni', 'SERRA RAJA, ABRIL'),
    ('Alevi Femeni', 'SALA RUIZ, JÚLIA'),
    ('Alevi Femeni', 'GUIXE PUGA, LAIA'),

    ('Infantil-Cadet Femeni', 'BARRERA HARO, PAULA'),
    ('Infantil-Cadet Femeni', 'COROMINAS BECH, EMMA'),
    ('Infantil-Cadet Femeni', 'GENER DAM, MARTINA'),
    ('Infantil-Cadet Femeni', 'GIMENEZ DRAGU, AITANA'),
    ('Infantil-Cadet Femeni', 'GUITART CASALS, LIA'),
    ('Infantil-Cadet Femeni', 'JODAR MARTIN, SARA'),
    ('Infantil-Cadet Femeni', 'NIETO RAMIREZ, AVRIL'),
    ('Infantil-Cadet Femeni', 'PEÑA MALPICA, IRENE'),
    ('Infantil-Cadet Femeni', 'SUNYER RIAL, MERCE'),
    ('Infantil-Cadet Femeni', 'UTIU, ANAMARIA'),
    ('Infantil-Cadet Femeni', 'SERRA RODRIGUEZ, ARLET'),
    ('Infantil-Cadet Femeni', 'SALA MIGUELES, IVET'),
    ('Infantil-Cadet Femeni', 'OSORIO CÁNOVAS, NOA'),
    ('Infantil-Cadet Femeni', 'GALERA ROMERO, MARIA'),
    ('Infantil-Cadet Femeni', 'ESPEJO PEÑA, AINA'),
    ('Infantil-Cadet Femeni', 'EL FILALI LAMKALCHA, MANAR'),
    ('Infantil-Cadet Femeni', 'BADIA TORRES, ANNA'),
    ('Infantil-Cadet Femeni', 'AVI JIMÉNEZ, CAROL'),
    ('Infantil-Cadet Femeni', 'GILABERT SERRA, AINA'),
    ('Infantil-Cadet Femeni', 'OBIOLS MONTILLA, NOA'),
    ('Infantil-Cadet Femeni', 'AVI JIMÉNEZ, LINET'),
    ('Infantil-Cadet Femeni', 'COROMINAS BARRERA, GALA'),
    ('Infantil-Cadet Femeni', 'COTS ROMERO, BLANCA'),

    ('Juvenil Femeni', 'BADIA TORRES, IBETH'),
    ('Juvenil Femeni', 'COROMINAS BECH, ELIA'),
    ('Juvenil Femeni', 'ESQUIUS GARCIA, NÚRIA'),
    ('Juvenil Femeni', 'PEREZ RODRIGUEZ, LYDIA'),
    ('Juvenil Femeni', 'MASAS TORRENTS, ISIS'),
    ('Juvenil Femeni', 'GHAILAN BAZIOU, AYA'),
    ('Juvenil Femeni', 'CARDONA ESPLUGA, BRUNA'),
    ('Juvenil Femeni', 'ESTRUCH VALDIVIA, CRISTINA'),
    ('Juvenil Femeni', 'FONTAN SANCHEZ, JANA'),
    ('Juvenil Femeni', 'FREIXA FERNANDEZ, MARIA'),
    ('Juvenil Femeni', 'GONZALEZ TRISTANY, ANNA'),
    ('Juvenil Femeni', 'LARA CALLE, MARIA'),
    ('Juvenil Femeni', 'MASAS TORRENTS, IVET'),
    ('Juvenil Femeni', 'NAVAS DÍAZ-MADROÑERO, MARIONA'),
    ('Juvenil Femeni', 'NOVA GARCIA, JULIA'),
    ('Juvenil Femeni', 'TORRADAS HERNANDEZ, LAURA'),
    ('Juvenil Femeni', 'TRISTANY FERNANDEZ, BRUNA'),
    ('Juvenil Femeni', 'SANCHEZ PEREZ, CLOE'),
    ('Juvenil Femeni', 'RODRÍGUEZ FORTUNATO, ZAIRA'),

    ('Juvenil Masculi - A', 'ALISTE DURAN, ISAAC'),
    ('Juvenil Masculi - A', 'ANIORTE VERDEJO, JAN'),
    ('Juvenil Masculi - A', 'BADIA TORRES, JOSEP'),
    ('Juvenil Masculi - A', 'BOUZID, MOHAMED'),
    ('Juvenil Masculi - A', 'CANUDAS RIOBOÓ, JOAN'),
    ('Juvenil Masculi - A', 'FLORES MATA, JOAN'),
    ('Juvenil Masculi - A', 'GALERA ARNAU, ADRIÀ'),
    ('Juvenil Masculi - A', 'GONZALEZ GONZALEZ, ADRIA'),
    ('Juvenil Masculi - A', 'GONZALEZ MENDOZA, IAN'),
    ('Juvenil Masculi - A', 'ITURBE GALERA, AITOR'),
    ('Juvenil Masculi - A', 'MONTOYA XANDRI, MARÇAL'),
    ('Juvenil Masculi - A', 'OROZCO BORRERO, XAVI'),
    ('Juvenil Masculi - A', 'TORRES LALUEZA, VICTOR'),
    ('Juvenil Masculi - A', 'BARRERA TAPIA, XAVI'),
    ('Juvenil Masculi - A', 'BOIXADERA BALLARA, MARC'),
    ('Juvenil Masculi - A', 'COMPANY SORIANO, ERIC'),
    ('Juvenil Masculi - A', 'CEESAY, BACARY'),
    ('Juvenil Masculi - A', 'SERRA RODRIGUEZ, POL'),
    ('Juvenil Masculi - A', 'SERRA VAY, BIEL'),
    ('Juvenil Masculi - A', 'FORASTER TRULLOLS, JORDI'),
    ('Juvenil Masculi - A', 'MUÑOZ BARRANCO, DAVID'),
    ('Juvenil Masculi - A', 'RUIZ FÍGULS, MARC'),
    ('Juvenil Masculi - A', 'SALVADOR SOTO, PABLO'),

    ('Juvenil Masculi - B', 'ALISTE DURAN, ISAAC'),
    ('Juvenil Masculi - B', 'ANIORTE VERDEJO, JAN'),
    ('Juvenil Masculi - B', 'BADIA TORRES, JOSEP'),
    ('Juvenil Masculi - B', 'BOUZID, MOHAMED'),
    ('Juvenil Masculi - B', 'CANUDAS RIOBOÓ, JOAN'),
    ('Juvenil Masculi - B', 'FLORES MATA, JOAN'),
    ('Juvenil Masculi - B', 'GALERA ARNAU, ADRIÀ'),
    ('Juvenil Masculi - B', 'GONZALEZ GONZALEZ, ADRIA'),
    ('Juvenil Masculi - B', 'GONZALEZ MENDOZA, IAN'),
    ('Juvenil Masculi - B', 'ITURBE GALERA, AITOR'),
    ('Juvenil Masculi - B', 'MONTOYA XANDRI, MARÇAL'),
    ('Juvenil Masculi - B', 'OROZCO BORRERO, XAVI'),
    ('Juvenil Masculi - B', 'TORRES LALUEZA, VICTOR'),
    ('Juvenil Masculi - B', 'BARRERA TAPIA, XAVI'),
    ('Juvenil Masculi - B', 'BOIXADERA BALLARA, MARC'),
    ('Juvenil Masculi - B', 'COMPANY SORIANO, ERIC'),
    ('Juvenil Masculi - B', 'CEESAY, BACARY'),
    ('Juvenil Masculi - B', 'SERRA RODRIGUEZ, POL'),
    ('Juvenil Masculi - B', 'SERRA VAY, BIEL'),
    ('Juvenil Masculi - B', 'FORASTER TRULLOLS, JORDI'),
    ('Juvenil Masculi - B', 'MUÑOZ BARRANCO, DAVID'),
    ('Juvenil Masculi - B', 'RUIZ FÍGULS, MARC'),
    ('Juvenil Masculi - B', 'SALVADOR SOTO, PABLO'),

    ('Minis', 'BADIA RAMIREZ, ARAN'),
    ('Minis', 'BALLESTEROS MAS, MARC'),
    ('Minis', 'CABALLOL ROIG, MARC'),

    ('S7', 'JODAR MARTIN, ALAN'),
    ('S7', 'RAMIREZ TROBALON, LEO'),
    ('S7', 'TORRENTALLÉ BOIXADÉ, ADA'),

    ('S8', 'RIVAS CANO, EGAN'),
    ('S8', 'MARTINEZ FERRER, GERARD'),
    ('S8', 'GALERA MARMOL, MARTIN'),
    ('S8', 'CASTAÑO MOLINA, OLIVER'),
    ('S8', 'CARBALLO PUIKA, DAVID'),
    ('S8', 'BEKHAKH BEKHAKH, YOUSSEF'),
    ('S8', 'BECERRA LAFUENTE, HUGO'),
    ('S8', 'BARCO REQUENA, KAI'),
    ('S8', 'BALLESTEROS MAS, ROC'),
    ('S8', 'CASTAÑO SORIANO, CARLA'),

    ('S9', 'ROCA BARBERA, XAVI'),
    ('S9', 'MOLINA LOPEZ, BIEL'),
    ('S9', 'MARTÍ MARSIÑACH, CARLES'),
    ('S9', 'GASPAR GRAS, GAEL'),
    ('S9', 'FERNANDEZ PINTO, ALEIX'),
    ('S9', 'CABALLOL ROIG, GERARD'),
    ('S9', 'BORRÀS SALA, MARTÍ'),

    ('S10', 'NMILI EL MEKHIMAR, WAIL'),
    ('S10', 'NAVARRO TORNÉ, ARIÉ'),
    ('S10', 'GODOY LLORENS, LUCA'),
    ('S10', 'GODOY LLORENS, AIMAR'),
    ('S10', 'FIGOLS SOLER, DAVID'),
    ('S10', 'CLUSELLAS BERNADI, TON'),
    ('S10', 'CERA CARCELLÉ, ARAN'),
    ('S10', 'CAPARROS CALATAYUD, ARITZ'),
    ('S10', 'BALLESTEROS LIRIA, ÁLEX'),
    ('S10', 'BALAGUER PARRA, LLUC'),
    ('S10', 'BACARI DIALLO, MAMADOU BOBO'),
    ('S10', 'ARRABAL VILET, JOEL'),
    ('S10', 'ARIAS HERRERA, MARIO'),

    ('S11', 'SOLE GARCIA, JAUME'),
    ('S11', 'RUIZ ACOSTA, DANIEL'),
    ('S11', 'ROMLI EL AOUNI, AIMRAN'),
    ('S11', 'NAVARRO MOLNER, POL'),
    ('S11', 'MELERO RUIZ, JOSEP'),
    ('S11', 'LAYEL MOLINA, DENIS'),
    ('S11', 'FERNANDEZ PINTO, CARLES'),
    ('S11', 'EL GHOUL, HAROUN'),
    ('S11', 'CHAKROUN, SIRAJ'),
    ('S11', 'CASTAÑO SORIANO, SERGIO'),

    ('S12', 'ESPELT COMABELLA, MAX'),
    ('S12', 'GENER DAM, MARC'),
    ('S12', 'GODOY LLORENS, VALENTÍ'),
    ('S12', 'NAVARRO TORNÉ, QUER'),
    ('S12', 'SELGA FONT, MARC'),
    ('S12', 'VILLEGAS CODINA, QUIM'),

    ('S13', 'AL AABBAOUI JAMILI, MAHMOUD'),
    ('S13', 'ARNAU CASAHUGA, EUDALD'),
    ('S13', 'PALAU BELMONTE, ROC'),
    ('S13', 'CAMPS GALERA, PAU'),
    ('S13', 'COROMINAS ROLDAN, POL'),
    ('S13', 'FLORES SALA, MARC'),
    ('S13', 'JODAR ALTIMIRAS, MARCEL'),
    ('S13', 'LARA CALLE, MARTI'),
    ('S13', 'MARTIN SOTO, IKER'),
    ('S13', 'MARTINEZ FERRER, ALBERT'),
    ('S13', 'RIU SALA, GABRIEL'),
    ('S13', 'SEGURA COTS, QUIM'),
    ('S13', 'SERRA BADIA, ISAAC'),

    ('S14', 'RAMIREZ GUTIERREZ, UNAY'),
    ('S14', 'VILLEGAS CODINA, PAU'),
    ('S14', 'TROBALON SALA, IGNASI'),
    ('S14', 'TEQUIZ MAYANQUER, JOSUA NICOLAS'),
    ('S14', 'SOTO GUERRERO, PABLO'),
    ('S14', 'SERRA RAJA, MARTI'),
    ('S14', 'NOGUÉS GAZA, MARC'),
    ('S14', 'JODAR ALTIMIRAS, GERARD'),
    ('S14', 'JANÉ MAÑOSA, ORIOL'),
    ('S14', 'GUITART SALA, ROGER'),
    ('S14', 'FERREIRO GARCIA, BRUNO'),
    ('S14', 'ESPELT COMABELLA, JORDI'),
    ('S14', 'DAVINS ANDREO, JOSEP'),
    ('S14', 'COMPANY ALOY, ROC'),
    ('S14', 'BALAGUER PARRA, ARNAU'),
    ('S14', 'ARRE TORNE, RUBEN'),

    ('S16 (Cadet)', 'BALLESTEROS LIRIA, RAÚL'),
    ('S16 (Cadet)', 'FLORES SALA, JOAN'),
    ('S16 (Cadet)', 'BARRERA ALBETS, ORIOL'),
    ('S16 (Cadet)', 'ESPEJO JURADO, RAUL'),
    ('S16 (Cadet)', 'GILABERT SERRA, XAVI'),
    ('S16 (Cadet)', 'LEAL CARABIA, RAMON'),
    ('S16 (Cadet)', 'MOLNER BOIXADERA, ROGER'),
    ('S16 (Cadet)', 'PUIG PRAT, MARTÍ'),
    ('S16 (Cadet)', 'RODRIGUEZ FORTUNATO, ALAN')
  ) as t(equip_nom, nom)
)
insert into jugador (equip_id, nom)
select e.id, v.nom
from v
join e on e.nom = v.equip_nom
on conflict (equip_id, nom) do nothing;
